# Generated by Django 4.0.6 on 2022-07-27 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='record',
            name='patient',
        ),
        migrations.AddField(
            model_name='record',
            name='appointment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='record.appointment'),
            preserve_default=False,
        ),
    ]
